server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: camunda-demo
  datasource:
    username: root
    password: 761341
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/camunda-demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC

camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: admin
  filter:
    create: All tasks

logging:
  level:
    org.camunda: debug